### ISSUE TITLE
Unknown vision tower using haotianliu's llava repo

### ISSUE THREAD

**Issue by pspdada** [yuezih/less-is-more#8]
Hello, when I use the official repository and environment of `haotianliu`'s `llava` repository, and follow the official installation methods:
``` bash
conda create -n llava python=3.10 -y
conda activate llava
pip install --upgrade pip  # enable PEP 660 support
pip install -e .
```
Since the EOS was trained based on the official LLaVA model. I try to load the EOS lora checkpoint with the following settings, where the EOS-23k-lora is the local path I download from `https://huggingface.co/yuezih/llava-v1.5-7b-selective-23k-lora` using `git clone`
``` python
model_path = "/root/llm-project/utils/models/models-checkpoint/llava-v1.5/EOS-23k-lora/"
model_base = "/root/llm-project/utils/models/models-repo/llava-v1.5-7b/"
model_name = "llava_lora_model"
```
The following code is to load the llava model using
``` python
tokenizer, model, image_processor, context_len = load_pretrained_model(
    args.model_path, args.model_base, args.model_name
)

```
Here I encounter an error `ValueError: Unknown vision tower: clip-vit-large-patch14-336` when loading the model. Why is this happening?

The whole traceback is below:
```
You are using a model of type llava to instantiate a model of type llava_llama. This is not supported for all configurations of models and can yield errors.
Loading LLaVA from base model...
Traceback (most recent call last):
  File "/root/llm-project/LLaVA/eval.py", line 35, in <module>
    eval_model(args)
  File "/root/llm-project/LLaVA/llava/eval/model_vqa.py", line 31, in eval_model
    tokenizer, model, image_processor, context_len = load_pretrained_model(
  File "/root/llm-project/LLaVA/llava/model/builder.py", line 57, in load_pretrained_model
    model = LlavaLlamaForCausalLM.from_pretrained(model_base, low_cpu_mem_usage=True, config=lora_cfg_pretrained, **kwargs)
  File "/root/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3594, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/root/llm-project/LLaVA/llava/model/language_model/llava_llama.py", line 46, in __init__
    self.model = LlavaLlamaModel(config)
  File "/root/llm-project/LLaVA/llava/model/language_model/llava_llama.py", line 38, in __init__
    super(LlavaLlamaModel, self).__init__(config)
  File "/root/llm-project/LLaVA/llava/model/llava_arch.py", line 35, in __init__
    self.vision_tower = build_vision_tower(config, delay_load=True)
  File "/root/llm-project/LLaVA/llava/model/multimodal_encoder/builder.py", line 15, in build_vision_tower
    raise ValueError(f'Unknown vision tower: {vision_tower}')
ValueError: Unknown vision tower: clip-vit-large-patch14-336
```

Meanwhile, I try to use another lora checkpoint trained based on LLaVA (HA-DPO https://github.com/opendatalab/HA-DPO), and use the same setting, it looks like there's no problem.
```
You are using a model of type llava to instantiate a model of type llava_llama. This is not supported for all configurations of models and can yield errors.
Loading LLaVA from base model...
/root/anaconda3/envs/llava/lib/python3.10/site-packages/huggingface_hub/file_download.py:797: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Loading checkpoint shards:   0%|                                                                                                                                                                                      | 0/2 [00:00<?, ?it/s]/root/anaconda3/envs/llava/lib/python3.10/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.72s/it]
Loading additional LLaVA weights...
Loading LoRA weights...
Merging LoRA weights...
Model is loaded...
 36%|
```

Additional info:
After I installed the env of LLaVA, I encountered
```
ImportError: 
The new behaviour of LlamaTokenizer (with `self.legacy = False`) requires the protobuf library but it was not found in your environment. Checkout the instructions on the
installation page of its repo: https://github.com/protocolbuffers/protobuf/tree/master/python#installation and follow the ones
that match your environment. Please note that you may need to restart your runtime after installation.
```
So I install protobuf using `pip install protobuf`, which solve the ImportError.

**Comment by yuezih** [comment]
Hi @pspdada 
I haven't encountered a similar error, but I can try to help you locate it if you could provide a complete error message :)

**Comment by yuezih** [comment]
btw 你用LLaVA的官方代码，加载HA-DPO的checkpoint，为啥跑来我这里提issue啊 lolll

**Comment by pspdada** [comment]
> btw 你用LLaVA的官方代码，加载HA-DPO的checkpoint，为啥跑来我这里提issue啊 lolll

很抱歉我写错了给您带来了困扰，我已经修正了 issue 并提供了更详细的信息。

我的想法是 EOS 是 LLaVA 的一个 lora checkpoint，所以想用 LLaVA 的官方仓库和环境来跑 EOS 模型试试。但是会报错 `ValueError: Unknown vision tower: clip-vit-large-patch14-336`，请问你们的模型对于 LLaVA 官方模型有什么改动吗？为什么无法使用官方的仓库跑 EOS 模型呢？

类似的模型，诸如 HA-DPO 也是 LLaVA 的一个 lora checkpoint，我通过同样的方法可以成功加载 HA-DPO 模型

**Comment by yuezih** [comment]
我们用的也是 LLaVA 的官方代码，没做什么改动，按理说是可以正常加载的，其他人也没遇到相关问题。你方便贴一下完整的报错信息不

**Comment by pspdada** [comment]
> 我们用的也是 LLaVA 的官方代码，没做什么改动，按理说是可以正常加载的，其他人也没遇到相关问题。你方便贴一下完整的报错信息不

好的，我已经修改了 issue 的内容，并提供了更详细的信息

**Comment by pspdada** [comment]
我通过
``` python
model_path = "/root/llm-project/utils/models/models-checkpoint/llava-v1.5/EOS-23k-lora/"
# model_path = "/root/llm-project/utils/models/models-checkpoint/llava-v1.5/ha-dpo-lora/"
model_base = "/root/llm-project/utils/models/models-repo/llava-v1.5-7b/"
model_name = "llava_lora_model"
```
的方式来切换加载不同的 lora checkpoints，看起来 EOS 在 `load_pretrained_model()` 的下面这部分报错了：
``` python
    if 'llava' in model_name.lower():
        # Load LLaVA model
        if 'lora' in model_name.lower() and model_base is None:
            warnings.warn('There is `lora` in model name but no `model_base` is provided. If you are loading a LoRA model, please provide the `model_base` argument. Detailed instruction: https://github.com/haotian-liu/LLaVA#launch-a-model-worker-lora-weights-unmerged.')
        if 'lora' in model_name.lower() and model_base is not None:
            from llava.model.language_model.llava_llama import LlavaConfig
            lora_cfg_pretrained = LlavaConfig.from_pretrained(model_path)
            tokenizer = AutoTokenizer.from_pretrained(model_base, use_fast=False)
            print('Loading LLaVA from base model...')
            model = LlavaLlamaForCausalLM.from_pretrained(model_base, low_cpu_mem_usage=True, config=lora_cfg_pretrained, **kwargs) # ValueError Here
```

**Comment by yuezih** [comment]
可以改下这里的 config，改成你本地 clip 的路径：
https://huggingface.co/yuezih/llava-v1.5-7b-selective-23k-lora/blob/main/config.json#L25

**Comment by pspdada** [comment]
> 可以改下这里的 config，改成你本地 clip 的路径： https://huggingface.co/yuezih/llava-v1.5-7b-selective-23k-lora/blob/main/config.json#L25

感谢您的回复，我发现了 EOS 的 config.json 和 LLaVA 的不同之处，
在 `yuezih/llava-v1.5-7b-selective-23k-lora` 中
```
"mm_vision_tower": "clip-vit-large-patch14-336",
```
但是在 `liuhaotian/llava-v1.5-7b`中
```
"mm_vision_tower": "openai/clip-vit-large-patch14-336",
```
这看起来就是找不到 vision tower 的原因。我修改成下面这个之后，一切都正常了
